name: Python CI - TechFlow Tasks

# Define quando o pipeline será executado
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código do seu repositório para o servidor do GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configura a versão do Python no servidor
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Instala as dependências listadas no seu requirements.txt [cite: 66, 67]
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Executa os testes automatizados com Pytest [cite: 51, 114]
    - name: Run tests with pytest
      run: |
        python -m pytest